// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  ActionResult,
} from "./types";

export const params = {
  label: __t.string(),
  fullName: __t.string(),
  line1: __t.string(),
  line2: __t.string(),
  city: __t.string(),
  state: __t.string(),
  zip: __t.string(),
};
export const returnType = ActionResult