// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  ActionResult,
} from "./types";

export const params = {
  nickname: __t.string(),
  nameOnCard: __t.string(),
  brand: __t.string(),
  last4: __t.string(),
  expMonth: __t.i32(),
  expYear: __t.i32(),
  addressId: __t.string(),
};
export const returnType = ActionResult