// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  ActionResult,
} from "./types";

export const params = {
  text: __t.string(),
  aiText: __t.string(),
  hasAction: __t.bool(),
  goalTitle: __t.string(),
  dollars: __t.f64(),
};
export const returnType = ActionResult