// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  goalId: __t.string().name("goal_id"),
  userId: __t.string().name("user_id"),
  squadId: __t.string().name("squad_id"),
  localDate: __t.string().name("local_date"),
  status: __t.string(),
  startedAt: __t.f64().name("started_at"),
  lastDistanceM: __t.f64().name("last_distance_m"),
  lastPingAt: __t.f64().name("last_ping_at"),
  attempts: __t.i32(),
  aiState: __t.string().name("ai_state"),
  aiReason: __t.string().name("ai_reason"),
  aiRoast: __t.string().name("ai_roast"),
});
