// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  ActionResult,
} from "./types";

export const params = {
  title: __t.string(),
  emoji: __t.string(),
  lat: __t.f64(),
  lng: __t.f64(),
  radiusM: __t.f64(),
  daysOfWeek: __t.byteArray(),
  deadlineMinutes: __t.i32(),
  minStayMinutes: __t.i32(),
  basePenaltyCents: __t.i32(),
  maxPenaltyCents: __t.i32(),
};
export const returnType = ActionResult