// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u8().primaryKey(),
  demoMode: __t.bool().name("demo_mode"),
  nextPhotoFails: __t.bool().name("next_photo_fails"),
  timeOffsetMs: __t.f64().name("time_offset_ms"),
  fakeOn: __t.bool().name("fake_on"),
  fakeLat: __t.f64().name("fake_lat"),
  fakeLng: __t.f64().name("fake_lng"),
  fakeAcc: __t.f64().name("fake_acc"),
});
