// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  seq: __t.u32(),
  squadId: __t.string().name("squad_id"),
  actorUserId: __t.string().name("actor_user_id"),
  kind: __t.string(),
  text: __t.string(),
  createdAt: __t.f64().name("created_at"),
  metaJson: __t.string().name("meta_json"),
});
