// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  userId: __t.string().name("user_id"),
  squadId: __t.string().name("squad_id"),
  title: __t.string(),
  emoji: __t.string(),
  lat: __t.f64(),
  lng: __t.f64(),
  radiusM: __t.f64().name("radius_m"),
  days: __t.byteArray(),
  deadlineMinutes: __t.i32().name("deadline_minutes"),
  minStayMinutes: __t.i32().name("min_stay_minutes"),
  basePenaltyCents: __t.i32().name("base_penalty_cents"),
  maxPenaltyCents: __t.i32().name("max_penalty_cents"),
  consecutiveFlakes: __t.i32().name("consecutive_flakes"),
  streak: __t.i32(),
  active: __t.bool(),
  createdAt: __t.f64().name("created_at"),
  lastEvaluatedDate: __t.string().name("last_evaluated_date"),
});
