// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.10.2 (commit 58d2a40718c59535fd5c267e836d473298eb84d5).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import ClaimBridgeReducer from "./claim_bridge_reducer";
import LogoutReducer from "./logout_reducer";
import OutboxDoneReducer from "./outbox_done_reducer";
import OutboxFailReducer from "./outbox_fail_reducer";
import OutboxRequeueReducer from "./outbox_requeue_reducer";
import ResetDemoReducer from "./reset_demo_reducer";
import SetDemoFlagsReducer from "./set_demo_flags_reducer";
import SetDemoModeReducer from "./set_demo_mode_reducer";

// Import all procedure arg schemas
import * as AddAddressProcedure from "./add_address_procedure";
import * as AddPaymentMethodProcedure from "./add_payment_method_procedure";
import * as AskBotProcedure from "./ask_bot_procedure";
import * as CancelCashoutProcedure from "./cancel_cashout_procedure";
import * as CancelWithdrawalProcedure from "./cancel_withdrawal_procedure";
import * as ChangeEmailProcedure from "./change_email_procedure";
import * as ChangePasswordProcedure from "./change_password_procedure";
import * as ClaimSeedUserProcedure from "./claim_seed_user_procedure";
import * as ConfirmBotActionProcedure from "./confirm_bot_action_procedure";
import * as CreateGoalProcedure from "./create_goal_procedure";
import * as CreateSquadProcedure from "./create_squad_procedure";
import * as FinishCheckinProcedure from "./finish_checkin_procedure";
import * as ForceFlakeProcedure from "./force_flake_procedure";
import * as GetSecurityQuestionIdsProcedure from "./get_security_question_ids_procedure";
import * as JoinSquadProcedure from "./join_squad_procedure";
import * as LoginProcedure from "./login_procedure";
import * as PingCheckinProcedure from "./ping_checkin_procedure";
import * as PostMessageProcedure from "./post_message_procedure";
import * as ProposeCashoutProcedure from "./propose_cashout_procedure";
import * as RegisterAccountProcedure from "./register_account_procedure";
import * as RegisterUserProcedure from "./register_user_procedure";
import * as RemoveAddressProcedure from "./remove_address_procedure";
import * as RemovePaymentMethodProcedure from "./remove_payment_method_procedure";
import * as RequestWithdrawalProcedure from "./request_withdrawal_procedure";
import * as ResetPasswordProcedure from "./reset_password_procedure";
import * as SetPlanTierProcedure from "./set_plan_tier_procedure";
import * as SetPoolGoalProcedure from "./set_pool_goal_procedure";
import * as StartCheckinProcedure from "./start_checkin_procedure";
import * as UpdateAccountNameProcedure from "./update_account_name_procedure";
import * as UpdateAvatarProcedure from "./update_avatar_procedure";
import * as UpdateGoalPenaltyProcedure from "./update_goal_penalty_procedure";
import * as UpdateSecurityProcedure from "./update_security_procedure";
import * as VerifySecurityAnswersProcedure from "./verify_security_answers_procedure";
import * as VoteCashoutProcedure from "./vote_cashout_procedure";

// Import all table schema definitions
import BridgeLinksRow from "./bridge_links_table";
import BridgeOutboxRow from "./bridge_outbox_table";
import CashoutRow from "./cashout_table";
import CashoutVoteRow from "./cashout_vote_table";
import CheckinRow from "./checkin_table";
import DemoFlagsRow from "./demo_flags_table";
import FeedEventRow from "./feed_event_table";
import GoalRow from "./goal_table";
import MyAccountRow from "./my_account_table";
import MyAddressesRow from "./my_addresses_table";
import MyBillingPlanRow from "./my_billing_plan_table";
import MyBotMessagesRow from "./my_bot_messages_table";
import MyPaymentMethodsRow from "./my_payment_methods_table";
import MyUserRow from "./my_user_table";
import PenaltyRow from "./penalty_table";
import SquadRow from "./squad_table";
import UserRow from "./user_table";
import WithdrawalRow from "./withdrawal_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  cashout: __table({
    name: 'cashout',
    indexes: [
      { accessor: 'id', name: 'cashout_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'squadId', name: 'cashout_squad_id_idx_btree', algorithm: 'btree', columns: [
        'squadId',
      ] },
    ],
    constraints: [
      { name: 'cashout_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CashoutRow),
  cashoutVote: __table({
    name: 'cashout_vote',
    indexes: [
      { accessor: 'id', name: 'cashout_vote_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'proposalId', name: 'cashout_vote_proposal_id_idx_btree', algorithm: 'btree', columns: [
        'proposalId',
      ] },
      { accessor: 'squadId', name: 'cashout_vote_squad_id_idx_btree', algorithm: 'btree', columns: [
        'squadId',
      ] },
    ],
    constraints: [
      { name: 'cashout_vote_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CashoutVoteRow),
  checkin: __table({
    name: 'checkin',
    indexes: [
      { accessor: 'goalId', name: 'checkin_goal_id_idx_btree', algorithm: 'btree', columns: [
        'goalId',
      ] },
      { accessor: 'id', name: 'checkin_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'squadId', name: 'checkin_squad_id_idx_btree', algorithm: 'btree', columns: [
        'squadId',
      ] },
      { accessor: 'userId', name: 'checkin_user_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'checkin_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CheckinRow),
  demoFlags: __table({
    name: 'demo_flags',
    indexes: [
      { accessor: 'id', name: 'demo_flags_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'demo_flags_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DemoFlagsRow),
  feedEvent: __table({
    name: 'feed_event',
    indexes: [
      { accessor: 'id', name: 'feed_event_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'squadId', name: 'feed_event_squad_id_idx_btree', algorithm: 'btree', columns: [
        'squadId',
      ] },
    ],
    constraints: [
      { name: 'feed_event_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, FeedEventRow),
  goal: __table({
    name: 'goal',
    indexes: [
      { accessor: 'id', name: 'goal_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'squadId', name: 'goal_squad_id_idx_btree', algorithm: 'btree', columns: [
        'squadId',
      ] },
      { accessor: 'userId', name: 'goal_user_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'goal_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GoalRow),
  penalty: __table({
    name: 'penalty',
    indexes: [
      { accessor: 'goalId', name: 'penalty_goal_id_idx_btree', algorithm: 'btree', columns: [
        'goalId',
      ] },
      { accessor: 'id', name: 'penalty_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'key', name: 'penalty_key_idx_btree', algorithm: 'btree', columns: [
        'key',
      ] },
      { accessor: 'squadId', name: 'penalty_squad_id_idx_btree', algorithm: 'btree', columns: [
        'squadId',
      ] },
      { accessor: 'userId', name: 'penalty_user_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'penalty_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'penalty_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, PenaltyRow),
  squad: __table({
    name: 'squad',
    indexes: [
      { accessor: 'id', name: 'squad_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'inviteCode', name: 'squad_invite_code_idx_btree', algorithm: 'btree', columns: [
        'inviteCode',
      ] },
    ],
    constraints: [
      { name: 'squad_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SquadRow),
  user: __table({
    name: 'user',
    indexes: [
      { accessor: 'id', name: 'user_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'isSeed', name: 'user_is_seed_idx_btree', algorithm: 'btree', columns: [
        'isSeed',
      ] },
      { accessor: 'squadId', name: 'user_squad_id_idx_btree', algorithm: 'btree', columns: [
        'squadId',
      ] },
    ],
    constraints: [
      { name: 'user_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, UserRow),
  withdrawal: __table({
    name: 'withdrawal',
    indexes: [
      { accessor: 'id', name: 'withdrawal_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'squadId', name: 'withdrawal_squad_id_idx_btree', algorithm: 'btree', columns: [
        'squadId',
      ] },
      { accessor: 'userId', name: 'withdrawal_user_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'withdrawal_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WithdrawalRow),
  bridgeLinks: __table({
    name: 'bridge_links',
    indexes: [
    ],
    constraints: [
    ],
  }, BridgeLinksRow),
  bridgeOutbox: __table({
    name: 'bridge_outbox',
    indexes: [
    ],
    constraints: [
    ],
  }, BridgeOutboxRow),
  myAccount: __table({
    name: 'my_account',
    indexes: [
    ],
    constraints: [
    ],
  }, MyAccountRow),
  myAddresses: __table({
    name: 'my_addresses',
    indexes: [
    ],
    constraints: [
    ],
  }, MyAddressesRow),
  myBillingPlan: __table({
    name: 'my_billing_plan',
    indexes: [
    ],
    constraints: [
    ],
  }, MyBillingPlanRow),
  myBotMessages: __table({
    name: 'my_bot_messages',
    indexes: [
    ],
    constraints: [
    ],
  }, MyBotMessagesRow),
  myPaymentMethods: __table({
    name: 'my_payment_methods',
    indexes: [
    ],
    constraints: [
    ],
  }, MyPaymentMethodsRow),
  myUser: __table({
    name: 'my_user',
    indexes: [
    ],
    constraints: [
    ],
  }, MyUserRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("claim_bridge", ClaimBridgeReducer),
  __reducerSchema("logout", LogoutReducer),
  __reducerSchema("outbox_done", OutboxDoneReducer),
  __reducerSchema("outbox_fail", OutboxFailReducer),
  __reducerSchema("outbox_requeue", OutboxRequeueReducer),
  __reducerSchema("reset_demo", ResetDemoReducer),
  __reducerSchema("set_demo_flags", SetDemoFlagsReducer),
  __reducerSchema("set_demo_mode", SetDemoModeReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
  __procedureSchema("add_address", AddAddressProcedure.params, AddAddressProcedure.returnType),
  __procedureSchema("add_payment_method", AddPaymentMethodProcedure.params, AddPaymentMethodProcedure.returnType),
  __procedureSchema("ask_bot", AskBotProcedure.params, AskBotProcedure.returnType),
  __procedureSchema("cancel_cashout", CancelCashoutProcedure.params, CancelCashoutProcedure.returnType),
  __procedureSchema("cancel_withdrawal", CancelWithdrawalProcedure.params, CancelWithdrawalProcedure.returnType),
  __procedureSchema("change_email", ChangeEmailProcedure.params, ChangeEmailProcedure.returnType),
  __procedureSchema("change_password", ChangePasswordProcedure.params, ChangePasswordProcedure.returnType),
  __procedureSchema("claim_seed_user", ClaimSeedUserProcedure.params, ClaimSeedUserProcedure.returnType),
  __procedureSchema("confirm_bot_action", ConfirmBotActionProcedure.params, ConfirmBotActionProcedure.returnType),
  __procedureSchema("create_goal", CreateGoalProcedure.params, CreateGoalProcedure.returnType),
  __procedureSchema("create_squad", CreateSquadProcedure.params, CreateSquadProcedure.returnType),
  __procedureSchema("finish_checkin", FinishCheckinProcedure.params, FinishCheckinProcedure.returnType),
  __procedureSchema("force_flake", ForceFlakeProcedure.params, ForceFlakeProcedure.returnType),
  __procedureSchema("get_security_question_ids", GetSecurityQuestionIdsProcedure.params, GetSecurityQuestionIdsProcedure.returnType),
  __procedureSchema("join_squad", JoinSquadProcedure.params, JoinSquadProcedure.returnType),
  __procedureSchema("login", LoginProcedure.params, LoginProcedure.returnType),
  __procedureSchema("ping_checkin", PingCheckinProcedure.params, PingCheckinProcedure.returnType),
  __procedureSchema("post_message", PostMessageProcedure.params, PostMessageProcedure.returnType),
  __procedureSchema("propose_cashout", ProposeCashoutProcedure.params, ProposeCashoutProcedure.returnType),
  __procedureSchema("register_account", RegisterAccountProcedure.params, RegisterAccountProcedure.returnType),
  __procedureSchema("register_user", RegisterUserProcedure.params, RegisterUserProcedure.returnType),
  __procedureSchema("remove_address", RemoveAddressProcedure.params, RemoveAddressProcedure.returnType),
  __procedureSchema("remove_payment_method", RemovePaymentMethodProcedure.params, RemovePaymentMethodProcedure.returnType),
  __procedureSchema("request_withdrawal", RequestWithdrawalProcedure.params, RequestWithdrawalProcedure.returnType),
  __procedureSchema("reset_password", ResetPasswordProcedure.params, ResetPasswordProcedure.returnType),
  __procedureSchema("set_plan_tier", SetPlanTierProcedure.params, SetPlanTierProcedure.returnType),
  __procedureSchema("set_pool_goal", SetPoolGoalProcedure.params, SetPoolGoalProcedure.returnType),
  __procedureSchema("start_checkin", StartCheckinProcedure.params, StartCheckinProcedure.returnType),
  __procedureSchema("update_account_name", UpdateAccountNameProcedure.params, UpdateAccountNameProcedure.returnType),
  __procedureSchema("update_avatar", UpdateAvatarProcedure.params, UpdateAvatarProcedure.returnType),
  __procedureSchema("update_goal_penalty", UpdateGoalPenaltyProcedure.params, UpdateGoalPenaltyProcedure.returnType),
  __procedureSchema("update_security", UpdateSecurityProcedure.params, UpdateSecurityProcedure.returnType),
  __procedureSchema("verify_security_answers", VerifySecurityAnswersProcedure.params, VerifySecurityAnswersProcedure.returnType),
  __procedureSchema("vote_cashout", VoteCashoutProcedure.params, VoteCashoutProcedure.returnType),
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.10.2" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

