// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  userId: __t.string().name("user_id"),
  label: __t.string(),
  fullName: __t.string().name("full_name"),
  line1: __t.string().name("line_1"),
  line2: __t.string().name("line_2"),
  city: __t.string(),
  state: __t.string(),
  zip: __t.string(),
  createdAt: __t.f64().name("created_at"),
});
