// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  userId: __t.string().name("user_id"),
  nickname: __t.string(),
  nameOnCard: __t.string().name("name_on_card"),
  brand: __t.string(),
  last4: __t.string().name("last_4"),
  expMonth: __t.i32().name("exp_month"),
  expYear: __t.i32().name("exp_year"),
  addressId: __t.string().name("address_id"),
  createdAt: __t.f64().name("created_at"),
});
