// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  key: __t.string(),
  goalId: __t.string().name("goal_id"),
  userId: __t.string().name("user_id"),
  squadId: __t.string().name("squad_id"),
  localDate: __t.string().name("local_date"),
  amountCents: __t.i32().name("amount_cents"),
  intendedCents: __t.i32().name("intended_cents"),
  shortfallCents: __t.i32().name("shortfall_cents"),
  status: __t.string(),
  createdAt: __t.f64().name("created_at"),
  nessieTransferId: __t.string().name("nessie_transfer_id"),
});
