// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  ActionResult,
  HashedAnswer,
} from "./types";

export const params = {
  firstName: __t.string(),
  lastName: __t.string(),
  email: __t.string(),
  username: __t.string(),
  passwordHash: __t.string(),
  get security() {
    return __t.array(HashedAnswer);
  },
};
export const returnType = ActionResult