// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  name: __t.string(),
  inviteCode: __t.string().name("invite_code"),
  poolGoalName: __t.string().name("pool_goal_name"),
  poolGoalCents: __t.i32().name("pool_goal_cents"),
  poolBalanceCents: __t.i32().name("pool_balance_cents"),
  timezone: __t.string(),
  relayLinked: __t.bool().name("relay_linked"),
});
