// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Account = __t.object("Account", {
  key: __t.string(),
  userId: __t.string(),
  username: __t.string(),
  email: __t.string(),
  firstName: __t.string(),
  lastName: __t.string(),
  passwordHash: __t.string(),
  securityJson: __t.string(),
});
export type Account = __Infer<typeof Account>;

export const AccountSelf = __t.object("AccountSelf", {
  userId: __t.string(),
  username: __t.string(),
  email: __t.string(),
  firstName: __t.string(),
  lastName: __t.string(),
  securityQuestionIds: __t.array(__t.string()),
});
export type AccountSelf = __Infer<typeof AccountSelf>;

export const ActionResult = __t.object("ActionResult", {
  ok: __t.bool(),
  error: __t.string(),
  metaJson: __t.string(),
  dataJson: __t.string(),
});
export type ActionResult = __Infer<typeof ActionResult>;

export const Address = __t.object("Address", {
  id: __t.string(),
  userId: __t.string(),
  label: __t.string(),
  fullName: __t.string(),
  line1: __t.string(),
  line2: __t.string(),
  city: __t.string(),
  state: __t.string(),
  zip: __t.string(),
  createdAt: __t.f64(),
});
export type Address = __Infer<typeof Address>;

export const AuthAttempt = __t.object("AuthAttempt", {
  key: __t.string(),
  n: __t.u32(),
  untilMs: __t.f64(),
});
export type AuthAttempt = __Infer<typeof AuthAttempt>;

export const BillingPlan = __t.object("BillingPlan", {
  userId: __t.string(),
  tier: __t.string(),
  trialEndsAt: __t.f64(),
});
export type BillingPlan = __Infer<typeof BillingPlan>;

export const BotMessage = __t.object("BotMessage", {
  id: __t.string(),
  userId: __t.string(),
  fromBot: __t.bool(),
  text: __t.string(),
  actionJson: __t.string(),
  createdAt: __t.f64(),
});
export type BotMessage = __Infer<typeof BotMessage>;

export const Bridge = __t.object("Bridge", {
  id: __t.u8(),
  identity: __t.identity(),
});
export type Bridge = __Infer<typeof Bridge>;

export const BridgeLinks = __t.object("BridgeLinks", {});
export type BridgeLinks = __Infer<typeof BridgeLinks>;

export const BridgeOutbox = __t.object("BridgeOutbox", {});
export type BridgeOutbox = __Infer<typeof BridgeOutbox>;

export const Cashout = __t.object("Cashout", {
  id: __t.string(),
  squadId: __t.string(),
  proposerUserId: __t.string(),
  merchantName: __t.string(),
  amountCents: __t.i32(),
  status: __t.string(),
  createdAt: __t.f64(),
  nessiePurchaseId: __t.string(),
});
export type Cashout = __Infer<typeof Cashout>;

export const CashoutVote = __t.object("CashoutVote", {
  id: __t.string(),
  proposalId: __t.string(),
  squadId: __t.string(),
  userId: __t.string(),
  approve: __t.bool(),
});
export type CashoutVote = __Infer<typeof CashoutVote>;

export const Checkin = __t.object("Checkin", {
  id: __t.string(),
  goalId: __t.string(),
  userId: __t.string(),
  squadId: __t.string(),
  localDate: __t.string(),
  status: __t.string(),
  startedAt: __t.f64(),
  lastDistanceM: __t.f64(),
  lastPingAt: __t.f64(),
  attempts: __t.i32(),
  aiState: __t.string(),
  aiReason: __t.string(),
  aiRoast: __t.string(),
});
export type Checkin = __Infer<typeof Checkin>;

export const Counter = __t.object("Counter", {
  name: __t.string(),
  n: __t.u32(),
});
export type Counter = __Infer<typeof Counter>;

export const DeadlineTick = __t.object("DeadlineTick", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type DeadlineTick = __Infer<typeof DeadlineTick>;

export const DemoFlags = __t.object("DemoFlags", {
  id: __t.u8(),
  demoMode: __t.bool(),
  nextPhotoFails: __t.bool(),
  timeOffsetMs: __t.f64(),
  fakeOn: __t.bool(),
  fakeLat: __t.f64(),
  fakeLng: __t.f64(),
  fakeAcc: __t.f64(),
});
export type DemoFlags = __Infer<typeof DemoFlags>;

export const DemoPatch = __t.object("DemoPatch", {
  setNextPhotoFails: __t.bool(),
  nextPhotoFails: __t.bool(),
  setFake: __t.bool(),
  fakeOn: __t.bool(),
  fakeLat: __t.f64(),
  fakeLng: __t.f64(),
  fakeAcc: __t.f64(),
  setOffset: __t.bool(),
  timeOffsetMs: __t.f64(),
});
export type DemoPatch = __Infer<typeof DemoPatch>;

export const FeedEvent = __t.object("FeedEvent", {
  id: __t.string(),
  seq: __t.u32(),
  squadId: __t.string(),
  actorUserId: __t.string(),
  kind: __t.string(),
  text: __t.string(),
  createdAt: __t.f64(),
  metaJson: __t.string(),
});
export type FeedEvent = __Infer<typeof FeedEvent>;

export const Goal = __t.object("Goal", {
  id: __t.string(),
  userId: __t.string(),
  squadId: __t.string(),
  title: __t.string(),
  emoji: __t.string(),
  lat: __t.f64(),
  lng: __t.f64(),
  radiusM: __t.f64(),
  days: __t.byteArray(),
  deadlineMinutes: __t.i32(),
  minStayMinutes: __t.i32(),
  basePenaltyCents: __t.i32(),
  maxPenaltyCents: __t.i32(),
  consecutiveFlakes: __t.i32(),
  streak: __t.i32(),
  active: __t.bool(),
  createdAt: __t.f64(),
  lastEvaluatedDate: __t.string(),
});
export type Goal = __Infer<typeof Goal>;

export const HashedAnswer = __t.object("HashedAnswer", {
  qId: __t.string(),
  answerHash: __t.string(),
});
export type HashedAnswer = __Infer<typeof HashedAnswer>;

export const Milestone = __t.object("Milestone", {
  key: __t.string(),
});
export type Milestone = __Infer<typeof Milestone>;

export const MsgRate = __t.object("MsgRate", {
  userId: __t.string(),
  timesJson: __t.string(),
});
export type MsgRate = __Infer<typeof MsgRate>;

export const MyAccount = __t.object("MyAccount", {});
export type MyAccount = __Infer<typeof MyAccount>;

export const MyAddresses = __t.object("MyAddresses", {});
export type MyAddresses = __Infer<typeof MyAddresses>;

export const MyBillingPlan = __t.object("MyBillingPlan", {});
export type MyBillingPlan = __Infer<typeof MyBillingPlan>;

export const MyBotMessages = __t.object("MyBotMessages", {});
export type MyBotMessages = __Infer<typeof MyBotMessages>;

export const MyPaymentMethods = __t.object("MyPaymentMethods", {});
export type MyPaymentMethods = __Infer<typeof MyPaymentMethods>;

export const MyUser = __t.object("MyUser", {});
export type MyUser = __Infer<typeof MyUser>;

export const NessieLink = __t.object("NessieLink", {
  key: __t.string(),
  customerId: __t.string(),
  accountId: __t.string(),
});
export type NessieLink = __Infer<typeof NessieLink>;

export const Outbox = __t.object("Outbox", {
  id: __t.u64(),
  ik: __t.string(),
  kind: __t.string(),
  payload: __t.string(),
  status: __t.string(),
  attempts: __t.u32(),
  nextTryAt: __t.timestamp(),
  createdAt: __t.timestamp(),
  result: __t.string(),
});
export type Outbox = __Infer<typeof Outbox>;

export const PaymentMethod = __t.object("PaymentMethod", {
  id: __t.string(),
  userId: __t.string(),
  nickname: __t.string(),
  nameOnCard: __t.string(),
  brand: __t.string(),
  last4: __t.string(),
  expMonth: __t.i32(),
  expYear: __t.i32(),
  addressId: __t.string(),
  createdAt: __t.f64(),
});
export type PaymentMethod = __Infer<typeof PaymentMethod>;

export const Penalty = __t.object("Penalty", {
  id: __t.string(),
  key: __t.string(),
  goalId: __t.string(),
  userId: __t.string(),
  squadId: __t.string(),
  localDate: __t.string(),
  amountCents: __t.i32(),
  intendedCents: __t.i32(),
  shortfallCents: __t.i32(),
  status: __t.string(),
  createdAt: __t.f64(),
  nessieTransferId: __t.string(),
});
export type Penalty = __Infer<typeof Penalty>;

export const PendingAction = __t.object("PendingAction", {
  id: __t.string(),
  userId: __t.string(),
  label: __t.string(),
  argsJson: __t.string(),
  expiresAt: __t.f64(),
});
export type PendingAction = __Infer<typeof PendingAction>;

export const ResetToken = __t.object("ResetToken", {
  key: __t.string(),
  token: __t.string(),
  expiresMs: __t.f64(),
});
export type ResetToken = __Infer<typeof ResetToken>;

export const Session = __t.object("Session", {
  identity: __t.identity(),
  userId: __t.string(),
});
export type Session = __Infer<typeof Session>;

export const Squad = __t.object("Squad", {
  id: __t.string(),
  name: __t.string(),
  inviteCode: __t.string(),
  poolGoalName: __t.string(),
  poolGoalCents: __t.i32(),
  poolBalanceCents: __t.i32(),
  timezone: __t.string(),
  relayLinked: __t.bool(),
});
export type Squad = __Infer<typeof Squad>;

export const User = __t.object("User", {
  id: __t.string(),
  name: __t.string(),
  avatar: __t.string(),
  squadId: __t.string(),
  balanceCents: __t.i32(),
  isSeed: __t.bool(),
});
export type User = __Infer<typeof User>;

export const Withdrawal = __t.object("Withdrawal", {
  id: __t.string(),
  userId: __t.string(),
  squadId: __t.string(),
  amountCents: __t.i32(),
  status: __t.string(),
  destination: __t.string(),
  createdAt: __t.f64(),
  availableAt: __t.f64(),
  nessieWithdrawalId: __t.string(),
});
export type Withdrawal = __Infer<typeof Withdrawal>;

