// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  userId: __t.string().name("user_id"),
  squadId: __t.string().name("squad_id"),
  amountCents: __t.i32().name("amount_cents"),
  status: __t.string(),
  destination: __t.string(),
  createdAt: __t.f64().name("created_at"),
  availableAt: __t.f64().name("available_at"),
  nessieWithdrawalId: __t.string().name("nessie_withdrawal_id"),
});
