// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import BackfillSquadOwnersReducer from "../backfill_squad_owners_reducer";
import ClaimBridgeReducer from "../claim_bridge_reducer";
import EnforceGoalLimitsReducer from "../enforce_goal_limits_reducer";
import LogoutReducer from "../logout_reducer";
import OutboxDoneReducer from "../outbox_done_reducer";
import OutboxFailReducer from "../outbox_fail_reducer";
import OutboxRequeueReducer from "../outbox_requeue_reducer";
import ResetDemoReducer from "../reset_demo_reducer";
import SetDemoFlagsReducer from "../set_demo_flags_reducer";
import SetDemoModeReducer from "../set_demo_mode_reducer";

export type BackfillSquadOwnersParams = __Infer<typeof BackfillSquadOwnersReducer>;
export type ClaimBridgeParams = __Infer<typeof ClaimBridgeReducer>;
export type EnforceGoalLimitsParams = __Infer<typeof EnforceGoalLimitsReducer>;
export type LogoutParams = __Infer<typeof LogoutReducer>;
export type OutboxDoneParams = __Infer<typeof OutboxDoneReducer>;
export type OutboxFailParams = __Infer<typeof OutboxFailReducer>;
export type OutboxRequeueParams = __Infer<typeof OutboxRequeueReducer>;
export type ResetDemoParams = __Infer<typeof ResetDemoReducer>;
export type SetDemoFlagsParams = __Infer<typeof SetDemoFlagsReducer>;
export type SetDemoModeParams = __Infer<typeof SetDemoModeReducer>;

